definitions:
  models.Coin:
    properties:
      symbol:
        type: string
    type: object
  models.CoinExchange:
    properties:
      AmountConveted:
        type: number
      amount:
        type: number
      from:
        type: string
      to:
        type: string
    type: object
  models.DefaultError:
    properties:
      errors:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  license: {}
paths:
  /coin:
    delete:
      consumes:
      - application/json
      description: Delete a Coin in the pool
      parameters:
      - description: Request symbol
        in: path
        name: Request
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Coin'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.DefaultError'
      summary: Index coin
      tags:
      - coin
    get:
      description: Return all the coin on the pool of avalable coins
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Coin'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.DefaultError'
      summary: Index coin
      tags:
      - coin
    post:
      consumes:
      - application/json
      description: Create a Coin in the pool
      parameters:
      - description: Request Body
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/models.Coin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Coin'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.DefaultError'
      summary: Index coin
      tags:
      - coin
  /price-conversion:
    get:
      consumes:
      - application/json
      description: Convert an amount of one cryptocurrency or fiat currency into one
        different currencies
      parameters:
      - description: Request from
        in: query
        name: from
        required: true
        type: string
      - description: Request to
        in: query
        name: to
        required: true
        type: string
      - description: Request amount
        in: query
        name: amount
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CoinExchange'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.DefaultError'
      summary: Index Conversor
      tags:
      - Conversor
swagger: "2.0"
